name: biblm
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python #==3.10
  - ipython
  - jupyter
  - ipykernel
  - langchain #~=0.0.352
  - langchain-community
  - langchain-core
  - langchain-huggingface
  - pypdf
  - sentence-transformers #==2.2.2
  - huggingface_hub
  - huggingface_accelerate
  - transformers #~=4.36.2
  - faiss-gpu
