name: gpu_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - jupyter
  - ipykernel
  - langchain
  - langchain-community
  - langchain-core
  - langchain-huggingface
  - pypdf
  - sentence-transformers
  - huggingface_hub
  - accelerate
  - transformers
  - faiss-gpu
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
